
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>

    <h3>This is your project's main page</h3>
    
    <h2>Este es una prueba de video</h2>
    <video src="<?php echo $this->baseUrl() ?>/videos/Wildlife.wmv">Tu navegador no soporta HTML5 </video>

<iframe width="560" height="315" src="//www.youtube.com/embed/2vjPBrBU-TM" frameborder="0" allowfullscreen></iframe>

<iframe width="560" height="315" src="<?php echo $this->baseUrl() ?>/videos/Wildlife.wmv" frameborder="0" allowfullscreen></iframe>

    <div id="more-information">
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
    </div>
</div>